### ISSUE TITLE
Is it possible to set a different order for different view ports?

### ISSUE THREAD

**Issue by inhopj** [anthinkingcoder/simple-grid#2]
<Row type="flex">
            <Col
                :xs="{ span: 8, offset: 1, order: 1}"
                :sm="{ span: 8, offset: 1, order: 2}"
                class="yellow-col">
            </Col>

            <Col
                :xs="{ span: 8, offset: 1, order: 2}"
                :sm="{ span: 8, offset: 1, order: 1}"
                class="green-col">
            </Col>
</Row>

**Comment by anthinkingcoder** [comment]
This is possible，I updated the version, and the current version is supported，but auto responsvice
order value can only `1-24`, beacuse span value can only `1-24`，
```
<Col
            :xs="{ span: 8, offset: 1, order: 2}"
            :sm="{ span: 8, offset: 1, order: 1}"
            class="green-col">
        </Col>
```
but if you do that,auto responsvice order  will be covered by `order=3`
```
<Col
            :xs="{ span: 8, offset: 1, order: 2}"
            :sm="{ span: 8, offset: 1, order: 1}"
            :order="3"
            class="green-col">
        </Col>
```
